const std = @import("std");
const core_mod = @import("core");

pub fn main() !void {
    const file = try std.fs.cwd().createFile("src/drivers/js/codegen-generated.js", .{});
    var output = std.io.bufferedWriter(file.writer());
    defer output.flush() catch {};

    try output.writer().print("// This is generated by the codegen. Please don't touch this file.\n" ++
        \\export const kiviInstanceSize = {any};
    , .{@sizeOf(core_mod.Kivi)});
}
